# -*- coding: utf-8 -*-
"""Password Validator Program

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fAmsNz-1UPxo4ANqpUjheFjDehSktmrx

### **Problem Statement**
The task is to create a program that checks the validity of a user-provided password. The program should apply specific rules and criteria to determine whether the given password meets the required security standards

## **Password Criteria:**

- **Minimum Length:** The password should have at least 8 characters.
- **Combination of Character Types:** The password should include a mix of uppercase letters, lowercase letters, digits, and symbols.
- **Blank Space:** The password should not contain any blank space.
- **First Letter:** The password should only begin with a capital letter.
"""

                                                      ## CODE BODY ##

string = input("Please enter a password: \n")

## Declaring Variables

Caps_letters = []
Symbols = []
Numbers = []

count = 0
index = 1
isNum = 0
isSymbol = 0
isCaps = 0
Haveblank = 0
criteria = 0

## 1st part (Populating the empty variables)

for letter in range(ord("A"), ord("Z")+1):   ## Converting alphabets to unicode integer
    Caps_letters.append(chr(letter))

for number in range(1,9+1):
    Numbers.append(str(number))
Numbers.append("0")

Symbols = ["!", "@", "#", "$", "%", "^", "&", "*"]

## 2nd part (Counting the total characters in the string)

for characters in string:
    count += 1
total = count
index = 1

## 3rd part (Validating if the first letter is in caps)

for letter in Caps_letters:
    if string[0] == letter:
        isCaps = 1
        break

## 4th part (Validating if the string contains numbers, doesn't contain blanks, contains special characters)

while index < count:
    if isNum == 0:
        for j in Numbers:
            if (string[index] == j):
                isNum = 1
                break
    if Haveblank == 0:
        if (string[index] == " "):
            Haveblank += 1
    if isSymbol == 0:
        for symbol in Symbols:
            if string[index] == symbol:
                isSymbol = 1
                break
    index += 1

if total >= 8:
    criteria += 1
else:
    print("Password Invalid : Length is not greater than 8 characters")
if isCaps == 1:
    criteria += 1
else:
    print("Password Invalid: No Uppercase character found")
if isNum == 1:
    criteria += 1
else:
    print("Password Invalid : Not alphanumeric")
if Haveblank == 0:
    criteria += 1
else:
    print("Password Invalid : It contains a blank space")
if isSymbol == 1:
    criteria += 1
else:
    print("Password Invalid : No special character")
print(f"Total Criteria Passed: {criteria}/5")
if criteria == 5:
  print(f"Password Accepted.")
